language: node_js
node_js:
  - "8"

matrix:
  include:
  - name: "Server-Side Test Suite"
    env: TEST_DIR=nexus_server
  - name: "Client-Side Test Suite"
    env: TEST_DIR=nexus_client
        
script: cd $TEST_DIR && npm install && npm test